### ISSUE TITLE
Add Gimbal

### ISSUE THREAD

**Issue by srmainwaring** [ArduPilot/ardupilot_gazebo#37]
## Feature request

The original version of the project for Gazebo11 included a plugin for a small 2d gimbal. This request is to have the gimbal model updated to run in Gazebo Sim and for the plugin to be ported to work with the `gz-sim7` libraries.  

#### Desired outcome

- A small gimbal model is available to attach to the Iris quadcopter.
- The gimbal joints may be controlled using a suitable plugin.
- There is a  topic to which commands may be published to set the gimbal joint position.

#### Alternatives

The gimbal model is available for download from [Gimbal Small 2D](https://app.gazebosim.org/OpenRobotics/fuel/models/Gimbal%20Small%202D) but has not been ported to Gazebo Sim / PBS shading:

- It uses the deprecated material `<script>` element for specifying visual colours.
- It uses the plugin `libGimbalSmall2dPlugin` which does not work in Gazebo Sim.

#### Platform

[  ] All
[  ] AntennaTracker
[ x ] Copter
[ x ] Plane
[ x ] Rover
[ x ] Submarine

#### Additional context

- ArduPilot Discourse: [Gimbal does not move in Gazebo](https://discuss.ardupilot.org/t/gimbal-does-not-move-in-gazebo/36859)

**Comment by srmainwaring** [comment]
Tracking development on https://github.com/srmainwaring/ardupilot_gazebo-1/tree/srmainwaring/garden/gimbal-plugin

- [ ] Update `gimbal_small_2d model` to render in Gazebo Sim.
- [ ] Add an arm joint in `gimbal_small_2d` for an extra DOF.
- [ ] Update `iris_with_ardupilot` model to enable gimbal.
- [ ] Add plugin for joint position control (reuse `gz::sim::systems::JointPositionControl` if it works for nested models). 
- [ ] Add example world and configure the `ArduPilotPlugin` to forward servo commands to the joint position control topics.

### Progress 

Model, additional joint and camera sensor rendering correctly in Gazebo.

![gimbal3d](https://user-images.githubusercontent.com/24916364/208898781-3c5a125d-cca2-46a6-b896-5e994b89137c.png)

**Comment by chngdickson** [comment]
@srmainwaring How do we control said gimbal using ardupilot's plugin?

**Comment by srmainwaring** [comment]
> How do we control said gimbal using ardupilot's plugin?

@chngdickson, the PR https://github.com/ArduPilot/ardupilot_gazebo/pull/43 includes a note on how to control the gimbal from MAVProxy using RC overrides. The example is set up as a standard servo gimbal so you should be able to follow the wiki guide https://ardupilot.org/copter/docs/common-camera-gimbal.html with the Gazebo version.

**Comment by samiamlabs** [comment]
Hi @srmainwaring!

I have been trying to control the camera tilt on a simulated bluerov2 using ardusub and the camera tilt RC input (https://www.ardusub.com/developers/rc-input-and-output.html).

I used this and #43 as a reference. Controlling it using the gz topic works now, but I seem to be getting only a static value on control channel 16 (`<control channel="15">`) from the ardupilot gazebo plugin. This is the output channel used for tilt on the physical bluerov2 https://bluerobotics.com/store/comm-control-power/control/navigator/.

Do you happen to know if it should be possible to control a simulated camera gimbal this way using ardusub? I'm guessing I may need to add something to my .param file, but am not sure what, or where to find more info about it.

**Comment by srmainwaring** [comment]
Hi @samiamlabs,

We should be able to sort something out. This issue is closed now, so it would be better to follow up on ArduPilot Discourse (https://discuss.ardupilot.org/). If you add a topic that includes `gazebo`, `gimbal` and tag me we can pick it up there. May also be good to add the BlueROV2 model to ArduPilot/SITL_Models so we can provide a standard configuration with a few variants for common payloads.
